// scripts/set-env.mjs
// Runs before `ng build --configuration production`.
// Reads environment variables (set by Vercel or locally) and writes
// the Angular production environment file so values are baked in at build time.
//
// Required env vars:
//   API_URL              – full base URL of the .NET API, e.g. https://vin-loggen-api.onrender.com
//   SUPABASE_URL         – Supabase project URL
//   SUPABASE_ANON_KEY    – Supabase publishable anon key
// Optional env vars:
//   MAPBOX_TOKEN         – Mapbox public token (map view disabled when absent)

import { writeFileSync, mkdirSync } from 'fs';
import { dirname, join, resolve } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const outputPath = resolve(__dirname, '../src/environments/environment.prod.ts');

const required = ['API_URL', 'SUPABASE_URL', 'SUPABASE_ANON_KEY'];
const missing  = required.filter(k => !process.env[k]);
if (missing.length) {
  console.error(`[set-env] Missing required env vars: ${missing.join(', ')}`);
  process.exit(1);
}

const apiBaseUrl    = process.env['API_URL'].replace(/\/$/, '') + '/api';
const supabaseUrl   = process.env['SUPABASE_URL'];
const supabaseAnon  = process.env['SUPABASE_ANON_KEY'];
const mapboxToken   = process.env['MAPBOX_TOKEN'] ?? '';

const content = `// ⚠️  Auto-generated by scripts/set-env.mjs – do not edit by hand.
export const environment = {
  production: true,
  supabaseUrl: '${supabaseUrl}',
  supabaseAnonKey: '${supabaseAnon}',
  apiBaseUrl: '${apiBaseUrl}',
  mapboxToken: '${mapboxToken}',
} as const;
`;

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, content, 'utf-8');
console.log(`[set-env] Written ${outputPath}`);
console.log(`          apiBaseUrl  = ${apiBaseUrl}`);
console.log(`          supabaseUrl = ${supabaseUrl}`);
