// scripts/set-env-dev.mjs
// Generates environment.dev.ts for local / Docker development.
// Reads MAPBOX_TOKEN from the host environment (passed via docker-compose).
// Run before `ng serve` when you need Mapbox features locally.

import { writeFileSync, mkdirSync } from 'fs';
import { dirname, resolve } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const outputPath = resolve(__dirname, '../src/environments/environment.dev.ts');

const mapboxToken = process.env['MAPBOX_TOKEN'] ?? '';

const content = `// Auto-generated by scripts/set-env-dev.mjs – do not edit by hand.
export const environment = {
  production: false,
  supabaseUrl: 'https://quvkgyiybiyfwnjpembr.supabase.co',
  supabaseAnonKey: 'sb_publishable_HOSKA-LisfvKIj_Z61Wu1g_Ag8DnmPP',
  apiBaseUrl: '/api',
  mapboxToken: '${mapboxToken}',
} as const;
`;

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, content, 'utf-8');
console.log('[set-env-dev] Written', outputPath);
if (mapboxToken) {
  console.log('             mapboxToken = (set)');
} else {
  console.log('             mapboxToken = (empty – Mapbox features disabled)');
}
