// ⚠️  Auto-generated by scripts/set-env.mjs – do not edit by hand.
// Run `npm run build:prod` (with API_URL, SUPABASE_URL, SUPABASE_ANON_KEY set) to regenerate.
export const environment = {
  production: true,
  supabaseUrl: '',
  supabaseAnonKey: '',
  apiBaseUrl: '/api',
} as const;
